# 项目相关配置
ruoyi:
  name: RuoYi
  version: 3.9.0
  copyrightYear: 2025
  profile: ${UPLOAD_PATH:D:/ruoyi/uploadPath}
  addressEnabled: false
  captchaType: ${CAPTCHA_TYPE:math}

# 开发环境配置
server:
  port: ${API_PORT:8080}
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    maxRetryCount: 5
    lockTime: 10

# Spring配置
spring:
  messages:
    basename: i18n/messages
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DB:0}
    password: ${REDIS_PASS:}
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

# token配置
token:
  header: Authorization
  secret: ${TOKEN_SECRET:abcdefghijklmnopqrstuvwxyz}
  expireTime: ${TOKEN_EXPIRE_MINUTES:240}

# MyBatis配置
mybatis:
  typeAliasesPackage: com.ruoyi.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  enabled: ${SWAGGER_ENABLED:true}
  pathMapping: ${API_PREFIX:/por-api}

# 防止XSS攻击
xss:
  enabled: true
  excludes: /system/notice
  urlPatterns: /system/*,/monitor/*,/tool/*
